first_2/apps/CallBoard/urls.py
from django.urls import path

from . import views

app_name = 'advert'
urlpatterns = [
    path('', views.board, name = 'board'),
    path('advert_create/', views.leave_advert, name = 'leave_advert'),
    path('<int:advert_id>/', views.detail, name = 'detail'),
    path('<int:advert_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
]

first_2/apps/Home_Page/urls.py
from django.urls import path

from . import views

app_name = 'home_page'
urlpatterns = [
    path('', views.home_page, name = 'home_page'),
]

first_2/apps/Shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from first_2.settings import MEDIA_URL, MEDIA_ROOT
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.showcase, name = 'showcase'),
    path('<int:product_id>/', views.detail, name = 'detail'),
    path('<int:product_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
    path('product_create/', views.leave_product, name = 'leave_product'),
] 

first_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('advert/', include('CallBoard.urls')),
    path('', include('Home_Page.urls')),
    path('shop/', include('Shop.urls')),
    path('admin/', admin.site.urls),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

first_2/apps/CallBoard/models.py
import datetime
from django.db import models

from django.utils import timezone

class Advert(models.Model):
    advert_title = models.CharField('Название', max_length = 200)
    advert_text = models.TextField('Текст обьявления')
    pub_date = models.DateTimeField('Дата публикации')
    
    def __str__(self):
        return self.advert_title

    def was_published_resently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Comment(models.Model):
    go = models.ForeignKey(Advert, on_delete = models.CASCADE)
    author_name = models.CharField('Имя автора', max_length = 30)
    comment_text = models.CharField('Текст комментария', max_length = 200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'

first_2/apps/Home_Page/models.py
from django.db import models

# Create your models here.

first_2/apps/Shop/models.py
from django.db import models
import datetime
from django.utils import timezone
now = datetime.datetime.now()

#now = datetime.datetime.now()

class Product(models.Model):
    product_title = models.CharField('Название игры', max_length = 150)
    product_text = models.TextField('О товаре')
    product_image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    product_price = models.IntegerField()
    pub_date = models.DateTimeField('Дата публикации',auto_now_add=True)
    
    @property
    def photo_url(self):
        if self.product_image and hasattr(self.product_image, 'url'):
            return self.product_image.url

    def __str__(self):
        return self.product_title

    def was_published_resently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

class Comment(models.Model):
    go = models.ForeignKey(Product, on_delete = models.CASCADE)
    author_name = models.CharField('Имя автора', max_length = 30)
    comment_text = models.CharField('Текст комментария', max_length = 200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'
# Create your models here.

first_2/apps/Shop/forms.py
from django import forms
from Shop.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_title', 'product_text', 'product_image', 'product_price')

first_2/apps/CallBoard/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Advert, Comment
from django.urls import reverse
import datetime

now = datetime.datetime.now()

def board(request):
    latest_advert_list = Advert.objects.order_by('-pub_date')[:30]
    return render(request, 'CallBoard/list.html', {'latest_advert_list' : latest_advert_list})

def leave_advert(request):
    try:
        Advert.objects.create(
            advert_title = request.POST['name'],
            advert_text = request.POST['text'],
            pub_date = now
            )
    except:
        pass
    return render (request, 'CallBoard/leave.html',)


def detail(request, advert_id):
    try:
        a = Advert.objects.get(id = advert_id )
    except:
        raise Http404("Обьявление не найдено ^~^")

    latest_comments_list = a.comment_set.order_by('id')[:10]

    return render (request, 'CallBoard/detail.html', {'advert' : a, 'latest_comments_list' : latest_comments_list})

def leave_comment(request, advert_id):
    try:
        a = Advert.objects.get(id = advert_id )
    except:
        raise Http404("Обьявление не найдено ^~^")

    a.comment_set.create(author_name = request.user.username, comment_text = request.POST['text'])

    return HttpResponseRedirect(reverse('advert:detail', args = (a.id,)))






# Create your views here.

first_2/apps/Home_Page/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'Home_Page/home_page.html')
# Create your views here.

first_2/apps/Shop/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from .models import Product, Comment
from django.urls import reverse
from .forms import ProductForm
import datetime

def showcase(request):
    latest_product_list = Product.objects.order_by('-pub_date')
    return render(request, 'Shop/list.html', {'latest_product_list' : latest_product_list})

def detail(request, product_id):
    try:
        a = Product.objects.get(id = product_id )
    except:
        raise Http404("Товар не найден ^~^")

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render (request, 'Shop/detail.html', {'product' : a, 'latest_comments_list' : latest_comments_list})

def leave_comment(request, product_id):
    try:
        a = Product.objects.get(id = product_id )
    except:
        raise Http404("Товар не найден ^~^")
    a.comment_set.create(
        author_name =  request.user.username,
        comment_text = request.POST['text'])

    return HttpResponseRedirect(reverse('shop:detail', args = (a.id,)))

#def leave_product(request):
#    try:
#        Product.objects.create(
#            product_title = request.POST['name'],
#            product_text = request.POST['text'],
#            product_image = request.FILES['image'],
#            product_image = request.POST['image'],
#            product_price = request.POST['price'],
#            pub_date = now
#            )
#    except:
#        pass
#    return render (request, 'Shop/leave.html')

def leave_product(request):
    try:
        form = ProductForm()
        form =ProductForm(request.POST, request.FILES)
        if form.is_valid():
            if 'product_image' in request.FILES:
                form.product_image = request.FILES['product_image']
            form.save(commit=True)
            return HttpResponseRedirect('../')
        else:
            print(form.errors)
        return render(request, 'Shop/leave.html', {'form': form})
    except:
        raise Http404('Error')
# Create your views here.

first_2/templates/CallBoard/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{advert.advert_title}} {% endblock %}

{% block content %}
<div>

    <h2>{{advert.advert_title}}</h2>

    <p>{{advert.advert_text}}</p>

    <em>{{advert.pub_date}}</em>
    
    {% if advert.was_published_resently %}
        НОВОЕ!
    {% endif %}
    
    <hr>

    {% if latest_comments_list  %}

        {% for c in latest_comments_list  %}

            <p>
                <strong>{{c.author_name}}</strong>
                <p>{{c.comment_text}}</p>
            </p>

        {% endfor  %}
    {% else  %}
    Коментарии не найдены! станьте первым)
    {% endif  %}

    <hr>

    
        <form action="{% url 'advert:leave_comment' advert.id %}" method="POST" class="comment">

            {% csrf_token %}

            <textarea name= "text" required = "" placeholder="Текст коментария" class="comment"></textarea>

            <button type="submit" class="comment"><img src="{% static 'images/comment.png' %}" id = "comment"></button><br>

            
        </form>
</div>

{% endblock %}

first_2/templates/CallBoard/leave.html
{% extends 'base.html' %}

{% block title %}Создание обьявления{% endblock %}

{% block content %}

    
<h2>Редактирование:</h2>

<form action="{% url 'advert:leave_advert' %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Название обьявления" name = "name"><br>
    <textarea name= "text" required = "" placeholder="Текст обьявления"></textarea><br>
    

    <button type="submit" class="crt">Опубликовать</button>

</form>

{% endblock %}

first_2/templates/CallBoard/list.html
{% extends 'base.html' %}

{% block title %}Обьявления{% endblock %}


{% block content %}
    
    {% if latest_advert_list  %}

        <h1>Обьявления:</h1>
        <div class="list">
            {% for a in latest_advert_list %}
            <div class="advert">
                <h3 class="advert">
                    <a href="{% url 'advert:detail' a.id %}" class="advert">
                        •{{a.advert_title}}
                    </a>
                    <br>
                </h3>
            </div>
            {% endfor %}
        </div>
    {% else %}
        Обьявления ненайдены ^_^
    {% endif %}

    <h2>
        <a href="advert_create/" class="crt">Создать обьявление</a>
    </h2>

{% endblock %}

first_2/templates/Home_Page/home_page.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}
{% block back %}
{% endblock %}
{% block content %}

    <h2>
        <a href="advert/">Обьявления</a>
    </h2>
    <br>
    <h2>
        <a href="shop/">Магазин</a>
    </h2>
    <br>
    <h2>
        <a href="/">Профиль</a>
    </h2>

{% endblock %}

first_2/templates/Shop/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{advert.advert_title}} {% endblock %}

{% block content %}


    <hr>

    <h2>{{product.product_title}}</h2>
    
    <em>{{product.pub_date}}</em>
    
    {% if product.was_published_resently %}
            <dr>НОВОЕ!
    {% endif %}

    <br>
    <a href="/media/{{product.product_image}}">
    <img src="/media/{{product.product_image}}" class="image">
    </a>
    <p>{{product.product_text}}</p>

    <h3>Цена: {{product.product_price}}₽</h3>
    
    <hr>
    <hr>

    {% if latest_comments_list  %}

        {% for c in latest_comments_list  %}

            <p>
                <strong>{{c.author_name}}</strong>
                <p>{{c.comment_text}}</p>
            </p>

        {% endfor  %}
    {% else  %}
    Коментарии не найдены! станьте первым)
    {% endif  %}
    <hr>

    <form action="{% url 'shop:leave_comment' product.id %}" method="POST" class="comment">

        {% csrf_token %}

        <textarea name= "text" required = "" placeholder="Текст коментария" class="comment"></textarea>

        <button type="submit" class="comment"><img src="{% static 'images/comment.png' %}" id = "comment"></button><br>

        

    </form>

{% endblock %}

first_2/templates/Shop/leave.html
{% extends 'base.html' %}

{% block title %}Опубликовать товар{% endblock %}

{% load static %}

{% block content %}

    
<h2>Редактирование:</h2>

<!--form action="{% url 'shop:leave_product' %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Название товара" name = "name"><br>
    <textarea name= "text" required = "" placeholder="Описание товара"></textarea><br>
    <form method="FILES">
        <input type="file" name = "image" accept="image/*">
    </form><br>
    <input type="number" name="price" min="0.00" max="1000000" value="0.00"><br>

    <button type="submit">Опубликовать</button>

</form-->


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
<button type="submit">Опубликовать</button>

{% endblock %}

first_2/templates/Shop/list.html
{% extends 'base.html' %}

{% block title %}Магазин{% endblock %}

{% block content %}

    {% if latest_product_list  %}

        <h1>Товары:</h1>
        <div class="list">
            {% for a in latest_product_list %}
            <div class="advert">
                <h3 class="advert">
                    <a href="{% url 'shop:detail' a.id %}" class="advert">
                        •{{a.product_title}}
                    </a>
                    <br>
                </h3>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <br><h4>>>>Товары ненайдены ^_^</h4>
    {% endif %}

    <h2>
        <a href="product_create/" class="crt">Опубликовать товар</a>
    </h2>

{% endblock %}

first_2/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Мой сайт{% endblock %}</title>
        <link rel="SHORTCUT ICON" href='{% static "images/Game.png" %}' type="image/x-icon">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link href="https://fonts.googleapis.com/css?family=Arsenal|Comfortaa|Exo+2|Odibee+Sans&display=swap" rel="stylesheet">
    </head>
    <body>
        <wrapper>
            <img src="{% static 'images/bg.png'%}" id = "bg">
            <header>
                <div class="inner-header">
                        <div class="back">
                            {% block back %}
                                <a href="../" class="back" ><-назад</a>
                            {% endblock %}
                        </div>
                    <div class="void_1"></div>
                    
                    <!--div class="void_2"></div-->
                    {% if user.is_authenticated %}
                        <div class="profile">
                            <a href="{% url 'account_logout' %}" class="profile" >{{user.username}}</a>
                        </div>
                    {% else %} 
                        <div class="profile">
                            <a href= '{% url "account_signup" %}' class="profile" >Регистрация</a>
                        </div>
                        <div class="profile">
                            <a href= '{% url "account_login" %}' class="profile" >Войти</a>
                        </div>
                    {% endif %}
                    <form class="search">
                        <input type="text" class="search" placeholder="Искать здесь...">
                        <button class="search" type="submit"><span class="lupa"></span></button>
                    </form>
                    <div class="logo">
                        <p id="name">GAMEshop.net</p>
                        <img src="{% static 'images/Game.png'%}" id = "gamepad">
                    </div>
                    {% block header %}{% endblock %}
                    <div style="clear: both"></div>
                </div>
            </header>
            <div class="row">
                <content>
                    <div class="inner-content">
                        {% block content %}{% endblock %}
                        <div style="clear: both"></div>
                    </div>   
                </content>
                <sidebar>
                    <div class="inner-sidebar">
                        {% block sidebar %}{% endblock %}
                        <div style="clear: both"></div>
                    </div>
                </sidebar>
            </div>
            <footer>
                <div class="inner-footer">
                    {% block footer %}{% endblock %}
                    <div style="clear: both"></div>
                </div>
            </footer>
        </wrapper>
    </body>
</html>